### ISSUE TITLE
[ Suggestion] Make it easier to remove the weapons and shields

### ISSUE THREAD

**Issue by Zygus42** [Azuxul/ShowArmsStand#2]
Did some testing with diamond armor, sword and a shield.  You pretty much can't remove the weapon unless you first remove the chest piece, and you can't remove the shield unless you use the hand swapping tool again.  Really should be able to click at the arms or sword/shield and get them back in your hand.

Shields should go into the offhand without having to use the hand swapping tool.

The hand swapping tool should swap the hand items without removing the armor item you're clicking on (usually the chest piece).

**Comment by Azuxul** [comment]
Thanks for you suggest, i will aplly it for a new version in a few days.

**Comment by Azuxul** [comment]
Suggest has been applied !
